Bump `@typescript-eslint` dependencies
This is required in order to be able to update to eslint 8, otherwise it will error:

```
TypeError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.yml': Class extends value undefined is not a constructor or null
```

It is also necessary to bump to the version of `eslint-config-airbnb-typescript` that is compatible with the updated
`@typescript-eslint`.